/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.daw1.samuelrguez.gui;

import java.awt.event.KeyEvent;
import java.io.IOException;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import org.daw1.samuelrguez.motores.IMotor;

/**
 *
 * @author 34609
 */
public class GestionMotorJDialog extends javax.swing.JDialog {

    private static final java.awt.Color COLOR_ROJO = new java.awt.Color(204, 0, 0);
    private static final java.awt.Color COLOR_VERDE = new java.awt.Color(51, 102, 0);
    private static IMotor gestorFichero;

    /**
     * Creates new form GestionMotorJDialog
     */
    public GestionMotorJDialog(java.awt.Frame parent, boolean modal, IMotor gf) {
        super(parent, modal);
        gestorFichero = gf;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainjPanel = new javax.swing.JPanel();
        cuerpojPanel = new javax.swing.JPanel();
        anadirjPanel = new javax.swing.JPanel();
        insertarjPanel = new javax.swing.JPanel();
        anadirjTextField = new javax.swing.JTextField();
        anadirjButton = new javax.swing.JButton();
        estadoInsertarjPanel = new javax.swing.JPanel();
        estadoInsertarjLabel = new javax.swing.JLabel();
        borrarjPanel = new javax.swing.JPanel();
        borradojPanel = new javax.swing.JPanel();
        borrarjTextField = new javax.swing.JTextField();
        borrarjButton = new javax.swing.JButton();
        estadoBorrarjPanel = new javax.swing.JPanel();
        estadoBorrarjLabel = new javax.swing.JLabel();
        titulojPanel = new javax.swing.JPanel();
        titulojLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("DAW1 Wordle SamuelR");

        mainjPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainjPanel.setLayout(new java.awt.BorderLayout());

        cuerpojPanel.setBackground(new java.awt.Color(255, 255, 255));
        cuerpojPanel.setLayout(new java.awt.GridLayout(2, 1));

        anadirjPanel.setBackground(new java.awt.Color(255, 255, 255));
        anadirjPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Alta palabra", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(51, 51, 51))); // NOI18N
        anadirjPanel.setForeground(new java.awt.Color(51, 51, 51));
        anadirjPanel.setLayout(new java.awt.GridLayout(2, 1));

        insertarjPanel.setBackground(new java.awt.Color(255, 255, 255));

        anadirjTextField.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        anadirjTextField.setPreferredSize(new java.awt.Dimension(160, 23));
        anadirjTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                anadirjTextFieldKeyReleased(evt);
            }
        });
        insertarjPanel.add(anadirjTextField);

        anadirjButton.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        anadirjButton.setText("Añadir");
        anadirjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anadirjButtonActionPerformed(evt);
            }
        });
        insertarjPanel.add(anadirjButton);

        anadirjPanel.add(insertarjPanel);

        estadoInsertarjPanel.setBackground(new java.awt.Color(255, 255, 255));
        estadoInsertarjPanel.setLayout(new java.awt.GridBagLayout());

        estadoInsertarjLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        estadoInsertarjPanel.add(estadoInsertarjLabel, new java.awt.GridBagConstraints());

        anadirjPanel.add(estadoInsertarjPanel);

        cuerpojPanel.add(anadirjPanel);

        borrarjPanel.setBackground(new java.awt.Color(255, 255, 255));
        borrarjPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Borrado palabra", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(51, 51, 51))); // NOI18N
        borrarjPanel.setForeground(new java.awt.Color(51, 51, 51));
        borrarjPanel.setLayout(new java.awt.GridLayout(2, 1));

        borradojPanel.setBackground(new java.awt.Color(255, 255, 255));

        borrarjTextField.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        borrarjTextField.setPreferredSize(new java.awt.Dimension(160, 23));
        borrarjTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                borrarjTextFieldKeyReleased(evt);
            }
        });
        borradojPanel.add(borrarjTextField);

        borrarjButton.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        borrarjButton.setText("Borrar");
        borrarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarjButtonActionPerformed(evt);
            }
        });
        borradojPanel.add(borrarjButton);

        borrarjPanel.add(borradojPanel);

        estadoBorrarjPanel.setBackground(new java.awt.Color(255, 255, 255));
        estadoBorrarjPanel.setLayout(new java.awt.GridBagLayout());

        estadoBorrarjLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        estadoBorrarjPanel.add(estadoBorrarjLabel, new java.awt.GridBagConstraints());

        borrarjPanel.add(estadoBorrarjPanel);

        cuerpojPanel.add(borrarjPanel);

        mainjPanel.add(cuerpojPanel, java.awt.BorderLayout.CENTER);

        titulojPanel.setBackground(new java.awt.Color(255, 255, 255));
        titulojPanel.setLayout(new java.awt.GridBagLayout());

        titulojLabel.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        titulojLabel.setForeground(new java.awt.Color(51, 51, 51));
        titulojLabel.setText("Gestión motor");
        titulojPanel.add(titulojLabel, new java.awt.GridBagConstraints());

        mainjPanel.add(titulojPanel, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void anadirjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anadirjButtonActionPerformed
        addPalabra();
    }//GEN-LAST:event_anadirjButtonActionPerformed

    private void borrarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarjButtonActionPerformed
        removePalabra();
    }//GEN-LAST:event_borrarjButtonActionPerformed

    private void anadirjTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_anadirjTextFieldKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            addPalabra();
        }
    }//GEN-LAST:event_anadirjTextFieldKeyReleased

    private void borrarjTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_borrarjTextFieldKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            removePalabra();
        }
    }//GEN-LAST:event_borrarjTextFieldKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionMotorJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionMotorJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionMotorJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionMotorJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GestionMotorJDialog dialog = new GestionMotorJDialog(new javax.swing.JFrame(), true, gestorFichero);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private void addPalabra() {
        String s = this.anadirjTextField.getText().toLowerCase();
        this.estadoBorrarjLabel.setText("");
        this.anadirjTextField.setText("");
        if (s.length() == MainJFrame.TAMANO_PALABRA) {
            if (!gestorFichero.isPalabraInDiccionario(s)) {
                try {
                    if (gestorFichero.addPalabra(s)) {
                        this.estadoInsertarjLabel.setForeground(COLOR_VERDE);
                        this.estadoInsertarjLabel.setText("Se ha añadido correctamente: " + s);
                    }
                } catch (IOException | SQLException ex) {
                    JOptionPane.showMessageDialog(this, "ERROR: " + ex.getMessage());
                }
            } else {
                this.estadoInsertarjLabel.setForeground(COLOR_ROJO);
                this.estadoInsertarjLabel.setText("La palabra ya existe.");
            }
        } else {
            this.estadoInsertarjLabel.setForeground(COLOR_ROJO);
            this.estadoInsertarjLabel.setText("La palabra debe tener " + MainJFrame.TAMANO_PALABRA + " letras.");
        }
    }

    private void removePalabra() {
        String s = this.borrarjTextField.getText().toLowerCase();
        this.estadoInsertarjLabel.setText("");
        this.borrarjTextField.setText("");
        if (s.length() == MainJFrame.TAMANO_PALABRA) {
            try {
                if (gestorFichero.removePalabra(s)) {
                    this.estadoBorrarjLabel.setForeground(COLOR_VERDE);
                    this.estadoBorrarjLabel.setText("Se ha borrado correctamente: " + s);
                } else {
                    this.estadoBorrarjLabel.setForeground(COLOR_ROJO);
                    this.estadoBorrarjLabel.setText("La palabra no existe.");
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "ERROR: " + ex.getMessage());
            }
        } else {
            this.estadoBorrarjLabel.setForeground(COLOR_ROJO);
            this.estadoBorrarjLabel.setText("La palabra debe tener " + MainJFrame.TAMANO_PALABRA + " letras.");
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anadirjButton;
    private javax.swing.JPanel anadirjPanel;
    private javax.swing.JTextField anadirjTextField;
    private javax.swing.JPanel borradojPanel;
    private javax.swing.JButton borrarjButton;
    private javax.swing.JPanel borrarjPanel;
    private javax.swing.JTextField borrarjTextField;
    private javax.swing.JPanel cuerpojPanel;
    private javax.swing.JLabel estadoBorrarjLabel;
    private javax.swing.JPanel estadoBorrarjPanel;
    private javax.swing.JLabel estadoInsertarjLabel;
    private javax.swing.JPanel estadoInsertarjPanel;
    private javax.swing.JPanel insertarjPanel;
    private javax.swing.JPanel mainjPanel;
    private javax.swing.JLabel titulojLabel;
    private javax.swing.JPanel titulojPanel;
    // End of variables declaration//GEN-END:variables
}
